"""empty message

Revision ID: 743eec583a13
Revises: ca02e6b1349d
Create Date: 2024-09-16 13:32:03.864506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743eec583a13'
down_revision = 'ca02e6b1349d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('cost_in_credits', sa.String(length=50), nullable=False),
    sa.Column('length', sa.String(length=50), nullable=False),
    sa.Column('max_atmosphering_speed', sa.String(length=50), nullable=False),
    sa.Column('crew', sa.String(length=50), nullable=False),
    sa.Column('passengers', sa.String(length=50), nullable=False),
    sa.Column('cargo_capacity', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Starships')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_starship_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'starships', ['starship_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_starship_id_fkey', 'Starships', ['starship_id'], ['id'])

    op.create_table('Starships',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Starships_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('model', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cargo_capacity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cost_in_credits', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('length', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('max_atmosphering_speed', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('crew', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('passengers', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Starships_pkey')
    )
    op.drop_table('starships')
    # ### end Alembic commands ###
