"""empty message

Revision ID: ca02e6b1349d
Revises: bbd1072d6fbe
Create Date: 2024-09-16 12:42:52.781856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca02e6b1349d'
down_revision = 'bbd1072d6fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_in_credits', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('length', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('max_atmosphering_speed', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('crew', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('passengers', sa.String(length=50), nullable=False))

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eye_color', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=False))

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gravity', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('surface_water', sa.String(length=50), nullable=False))
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('surface_water')
        batch_op.drop_column('gravity')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('eye_color')

    with op.batch_alter_table('Starships', schema=None) as batch_op:
        batch_op.drop_column('passengers')
        batch_op.drop_column('crew')
        batch_op.drop_column('max_atmosphering_speed')
        batch_op.drop_column('length')
        batch_op.drop_column('cost_in_credits')

    # ### end Alembic commands ###
